version: '3'
services:
  web1:
    image: httpd:latest
    container_name: web1
    ports:
      - "8081:80"

  web2:
    image: httpd:latest
    container_name: web2
    ports:
      - "8082:80"

  nginx:
    image: nginx:latest
    container_name: load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
